### ISSUE TITLE
Composer: fix zendesk dependency for v2

### ISSUE THREAD

**Issue by Colmea** [mtymek/MtZendeskApi#1]
Hi,

*zendesk_api_client_php* is currently working on a new version, which is breaking your wrapper (new HttpClient, for instance).

I think you need to lock the version of this dependency to "1.*", and maybe I can help you to upgrade your module for the new zendesk api version ;) .

I will send a PR with the new composer.json !

**Comment by mtymek** [comment]
Thanks - I set version requirement to `^1.0`, which fixed the issue.

If you want to upgrade the module - sure, please do!

**Comment by Colmea** [comment]
Thanks @mtymek !

Actually I still have issues with service-manager dependency. You set it to 2.6 (0bfd2368), which is, since 2.5, a standalone package only for zf 2.5 and above (I think).

It means that zf 2.4 users (which is a LTS version) can't use this module.

Did you locked service-manager to 2.6 version for a reason ? Do you think 2.4 could works too ?

**Comment by mtymek** [comment]
No, I didn't have any specific reason for that. Just merged your PR.
